/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleguideRouteImport } from './routes/styleguide'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as StyleguideIndexRouteImport } from './routes/styleguide/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as StyleguideCardsRouteImport } from './routes/styleguide/cards'
import { Route as StyleguideButtonsRouteImport } from './routes/styleguide/buttons'
import { Route as StyleguideBadgesRouteImport } from './routes/styleguide/badges'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRecurringExpensesRouteImport } from './routes/_authenticated/recurring-expenses'

const StyleguideRoute = StyleguideRouteImport.update({
  id: '/styleguide',
  path: '/styleguide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const StyleguideIndexRoute = StyleguideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StyleguideRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const StyleguideCardsRoute = StyleguideCardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => StyleguideRoute,
} as any)
const StyleguideButtonsRoute = StyleguideButtonsRouteImport.update({
  id: '/buttons',
  path: '/buttons',
  getParentRoute: () => StyleguideRoute,
} as any)
const StyleguideBadgesRoute = StyleguideBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => StyleguideRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecurringExpensesRoute =
  AuthenticatedRecurringExpensesRouteImport.update({
    id: '/recurring-expenses',
    path: '/recurring-expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/styleguide': typeof StyleguideRouteWithChildren
  '/recurring-expenses': typeof AuthenticatedRecurringExpensesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/styleguide/badges': typeof StyleguideBadgesRoute
  '/styleguide/buttons': typeof StyleguideButtonsRoute
  '/styleguide/cards': typeof StyleguideCardsRoute
  '/styleguide/': typeof StyleguideIndexRoute
}
export interface FileRoutesByTo {
  '/recurring-expenses': typeof AuthenticatedRecurringExpensesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/styleguide/badges': typeof StyleguideBadgesRoute
  '/styleguide/buttons': typeof StyleguideButtonsRoute
  '/styleguide/cards': typeof StyleguideCardsRoute
  '/': typeof AuthenticatedIndexRoute
  '/styleguide': typeof StyleguideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/styleguide': typeof StyleguideRouteWithChildren
  '/_authenticated/recurring-expenses': typeof AuthenticatedRecurringExpensesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/styleguide/badges': typeof StyleguideBadgesRoute
  '/styleguide/buttons': typeof StyleguideButtonsRoute
  '/styleguide/cards': typeof StyleguideCardsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/styleguide/': typeof StyleguideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/styleguide'
    | '/recurring-expenses'
    | '/settings'
    | '/transactions'
    | '/auth/login'
    | '/auth/register'
    | '/styleguide/badges'
    | '/styleguide/buttons'
    | '/styleguide/cards'
    | '/styleguide/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/recurring-expenses'
    | '/settings'
    | '/transactions'
    | '/auth/login'
    | '/auth/register'
    | '/styleguide/badges'
    | '/styleguide/buttons'
    | '/styleguide/cards'
    | '/'
    | '/styleguide'
  id:
    | '__root__'
    | '/_authenticated'
    | '/styleguide'
    | '/_authenticated/recurring-expenses'
    | '/_authenticated/settings'
    | '/_authenticated/transactions'
    | '/auth/login'
    | '/auth/register'
    | '/styleguide/badges'
    | '/styleguide/buttons'
    | '/styleguide/cards'
    | '/_authenticated/'
    | '/styleguide/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  StyleguideRoute: typeof StyleguideRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/styleguide': {
      id: '/styleguide'
      path: '/styleguide'
      fullPath: '/styleguide'
      preLoaderRoute: typeof StyleguideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styleguide/': {
      id: '/styleguide/'
      path: '/'
      fullPath: '/styleguide/'
      preLoaderRoute: typeof StyleguideIndexRouteImport
      parentRoute: typeof StyleguideRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/styleguide/cards': {
      id: '/styleguide/cards'
      path: '/cards'
      fullPath: '/styleguide/cards'
      preLoaderRoute: typeof StyleguideCardsRouteImport
      parentRoute: typeof StyleguideRoute
    }
    '/styleguide/buttons': {
      id: '/styleguide/buttons'
      path: '/buttons'
      fullPath: '/styleguide/buttons'
      preLoaderRoute: typeof StyleguideButtonsRouteImport
      parentRoute: typeof StyleguideRoute
    }
    '/styleguide/badges': {
      id: '/styleguide/badges'
      path: '/badges'
      fullPath: '/styleguide/badges'
      preLoaderRoute: typeof StyleguideBadgesRouteImport
      parentRoute: typeof StyleguideRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recurring-expenses': {
      id: '/_authenticated/recurring-expenses'
      path: '/recurring-expenses'
      fullPath: '/recurring-expenses'
      preLoaderRoute: typeof AuthenticatedRecurringExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedRecurringExpensesRoute: typeof AuthenticatedRecurringExpensesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedRecurringExpensesRoute: AuthenticatedRecurringExpensesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface StyleguideRouteChildren {
  StyleguideBadgesRoute: typeof StyleguideBadgesRoute
  StyleguideButtonsRoute: typeof StyleguideButtonsRoute
  StyleguideCardsRoute: typeof StyleguideCardsRoute
  StyleguideIndexRoute: typeof StyleguideIndexRoute
}

const StyleguideRouteChildren: StyleguideRouteChildren = {
  StyleguideBadgesRoute: StyleguideBadgesRoute,
  StyleguideButtonsRoute: StyleguideButtonsRoute,
  StyleguideCardsRoute: StyleguideCardsRoute,
  StyleguideIndexRoute: StyleguideIndexRoute,
}

const StyleguideRouteWithChildren = StyleguideRoute._addFileChildren(
  StyleguideRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  StyleguideRoute: StyleguideRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
